In [1]:
import numpy as np
n = np.arange(27)
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [2]:
n = n.reshape(3,9)

In [3]:
print(n)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]


In [4]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [5]:
import cv2

In [6]:
im_g = cv2.imread("smallgray.png", 0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [7]:
im_g[2,2] = 150
cv2.imwrite("newsmallgray.png", im_g)

True

In [8]:
im_g2 = np.vstack((im_g,im_g))
im_g2

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 150,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 150,  97, 182]], dtype=uint8)

In [9]:
np.vsplit(im_g2, 2)


[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 150,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 150,  97, 182]], dtype=uint8)]

In [10]:
print(im_g2)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 150  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 150  97 182]]
